import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

// https://vitejs.dev/config/
// NOTE: The sitemap is generated by scripts/prerender.mjs from the same `routes`
// array used to prerender pages (single source of truth), with tiered priorities.
// robots.txt is served statically from public/robots.txt.
export default defineConfig(({ mode }) => {
  const isSSR = mode === 'ssr';

  return {
    plugins: [
      react(),
    ],
    resolve: {
      alias: isSSR ? [
        {
          find: 'gsap/ScrollTrigger',
          replacement: path.resolve(__dirname, 'src/lib/gsap-scroll-trigger-ssr-mock.ts'),
        },
        {
          find: '@gsap/react',
          replacement: path.resolve(__dirname, 'src/lib/gsap-react-ssr-mock.ts'),
        },
        {
          find: 'gsap',
          replacement: path.resolve(__dirname, 'src/lib/gsap-ssr-mock.ts'),
        },
      ] : [],
    },
    ssr: {
      noExternal: ['react-helmet-async'],
    },
    optimizeDeps: {
      exclude: ['lucide-react'],
    },
    server: {
      proxy: {
        '/api': {
          target: 'http://localhost:3000',
          changeOrigin: true,
          rewrite: (path) => path,
        },
      },
    },
  };
});
