import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import sitemap from 'vite-plugin-sitemap';
import path from 'path';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  const isSSR = mode === 'ssr';

  return {
    plugins: [
      react(),
      ...(!isSSR ? [sitemap({
        hostname: 'https://www.auto-cleanse.co.uk',
        dynamicRoutes: [
          '/',
          '/services',
          '/dpf-cleaning',
          '/postal-dpf',
          '/book',
          '/why-clean',
          '/maintenance',
          '/about',
          '/contact',
          '/pricing',
          '/how-it-works',
          '/fuel-savings-calculator',
          '/dpf-cleaning-devon',
          '/dpf-cleaning-totnes',
          '/ecu-remapping',
          '/ecu-remapping-locations',
          '/ecu-cloning',
          '/vehicle-performance-lookup',
          '/remapping-booking',
          '/dpf-cleaning-exeter',
          '/dpf-cleaning-plymouth',
          '/dpf-cleaning-torquay',
          '/dpf-cleaning-paignton',
          '/ecu-remapping-plymouth',
          '/ecu-remapping-exeter',
          '/ecu-remapping-torquay',
          '/ecu-remapping-paignton',
          '/ecu-remapping-newton-abbot',
          '/ecu-remapping-torbay',
          '/ecu-remapping-totnes',
          '/ecu-remapping-ivybridge',
          '/ecu-remapping-tavistock',
          '/ecu-remapping-kingsbridge',
          // Batch 2
          '/ecu-remapping-brixham',
          '/ecu-remapping-teignmouth',
          '/ecu-remapping-dawlish',
          '/ecu-remapping-ashburton',
          '/ecu-remapping-buckfastleigh',
          '/ecu-remapping-dartmouth',
          '/ecu-remapping-salcombe',
          '/ecu-remapping-okehampton',
          '/ecu-remapping-sidmouth',
          // Batch 3
          '/ecu-remapping-barnstaple',
          '/ecu-remapping-bideford',
          '/ecu-remapping-tiverton',
          '/ecu-remapping-honiton',
          '/ecu-remapping-axminster',
          '/ecu-remapping-crediton',
          '/ecu-remapping-cullompton',
          '/ecu-remapping-south-hams',
          '/ecu-remapping-east-devon',
          '/ecu-remapping-north-devon',
          // Batch 4 — service type pages
          '/mobile-ecu-remapping-devon',
          '/stage-1-remaps-devon',
          '/van-remapping-devon',
          '/performance-remapping-devon',
          '/diesel-remapping-devon',
          '/petrol-remapping-devon',
          '/4x4-remapping-devon',
          '/fleet-vehicle-remapping-devon',
          '/ecu-tuning-devon',
          // Vehicles
          '/audi-a3-remap',
          '/audi-a4-remap',
          '/audi-a5-remap',
          '/audi-a6-remap',
          '/audi-q5-remap',
          '/audi-s3-remap',
          '/audi-s4-remap',
          '/audi-rs3-remap',
          '/bmw-320d-remap',
          '/bmw-330d-remap',
          '/bmw-118d-remap',
          '/bmw-120d-remap',
          '/bmw-m140i-remap',
          '/bmw-m340i-remap',
          '/bmw-x5-remap',
          '/bmw-520d-remap',
          '/vw-golf-gti-remap',
          '/vw-golf-r-remap',
          '/vw-golf-gtd-remap',
          '/vw-transporter-remap',
          '/vw-amarok-remap',
          '/vw-passat-remap',
          '/vw-tiguan-remap',
          '/mercedes-a35-remap',
          '/mercedes-a45-remap',
          '/mercedes-c220-remap',
          '/mercedes-c63-remap',
          '/mercedes-glc63-remap',
          '/mercedes-sprinter-remap',
          '/mercedes-e220-remap',
          '/ford-transit-remap',
          '/ford-transit-custom-remap',
          '/ford-ranger-remap',
          '/ford-fiesta-st-remap',
          '/ford-focus-st-remap',
          '/ford-kuga-remap',
          '/ford-mondeo-remap',
          '/range-rover-sport-remap',
          '/range-rover-evoque-remap',
          '/range-rover-velar-remap',
          '/land-rover-discovery-remap',
          '/land-rover-defender-remap',
          '/range-rover-vogue-remap',
          '/vauxhall-vivaro-remap',
          '/vauxhall-astra-remap',
          '/vauxhall-corsa-remap',
          '/nissan-navara-remap',
          '/toyota-hilux-remap',
          '/peugeot-boxer-remap',
          '/renault-trafic-remap',
          '/seat-leon-remap',
          '/seat-ibiza-remap',
          '/skoda-octavia-remap',
          '/skoda-superb-remap',
          '/porsche-macan-remap',
          '/volvo-xc60-remap',
          '/volvo-xc90-remap',
          '/peugeot-208-remap',
          '/peugeot-3008-remap',
          '/renault-clio-remap',
          '/renault-megane-remap',
          '/citroen-berlingo-remap',
          '/dacia-duster-remap',
          '/fiat-500-remap',
          '/fiat-ducato-remap',
          '/mazda-cx-5-remap',
          '/nissan-qashqai-remap',
          '/nissan-juke-remap',
          '/toyota-land-cruiser-remap',
        ],
      })] : []),
    ],
    resolve: {
      alias: isSSR ? [
        {
          find: 'gsap/ScrollTrigger',
          replacement: path.resolve(__dirname, 'src/lib/gsap-scroll-trigger-ssr-mock.ts'),
        },
        {
          find: '@gsap/react',
          replacement: path.resolve(__dirname, 'src/lib/gsap-react-ssr-mock.ts'),
        },
        {
          find: 'gsap',
          replacement: path.resolve(__dirname, 'src/lib/gsap-ssr-mock.ts'),
        },
      ] : [],
    },
    ssr: {
      noExternal: ['react-helmet-async'],
    },
    optimizeDeps: {
      exclude: ['lucide-react'],
    },
    server: {
      proxy: {
        '/api': {
          target: 'http://localhost:3000',
          changeOrigin: true,
          rewrite: (path) => path,
        },
      },
    },
  };
});
